### ISSUE TITLE
Commit mailing list

### ISSUE THREAD

**Issue by skaller** [keean/zenscript#26]
Any chance of setting up a mailing list for commits, and using the GitHub hooks to send it commit messages?

**Comment by keean** [comment]
I thought you get notifications if you watch the repository.

**Comment by shelby3** [comment]
I sure hope this can be handled by Github and we don't have to maintain external applications in order users to interopt with Github optimally.

**Comment by skaller** [comment]
> On 7 Oct 2016, at 20:05, Keean Schupke <notifications@github.com> wrote:
> 
> I thought you get notifications if you watch the repository.

How do you do that?

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by svieira** [comment]
Go to https://github.com/keean/zenscript/subscription @skaller (or click on the "Watch" eye on the top right of this very page)

**Comment by skaller** [comment]
As far as I can tell, please correct me if I am wrong, this does not achieve my desired result. I wish to receive emails on each commit, and no others. A watch option which does this also sends email of other activity including any activity on these issue lists.

**Comment by keean** [comment]
@skaller I think this will work. I am going to try setting it up: https://help.github.com/enterprise/11.10.340/user/articles/receiving-email-notifications-for-pushes-to-a-repository/

**Comment by skaller** [comment]
You mean: https://help.github.com/articles/managing-notifications-for-pushes-to-a-repository/

This machinery works. However you only get 2 email addresses. The best way to do this is send it to an email list which people can subscribe to such as zenscript-builds@googlegroups.com. Clearly you will have to make that email account on gmail for that to work. I use this mechanism with the webhooks.

My project also uses the Travis and Appveyor continuous integration servers and these are also configured to send the build results to that list.

If using gmail be prepared for a little bit of pain. Gmail accounts do not accept email from everywhere, only from subscribers. To subscribe you have to verify your email address. Github obviously cannot do that. There is a work around, which I think goes like this: you tell GitHub to send the email with the email address of the committer as the sender, and then you make sure all committers are subscribed to the list. I think there is another way, where the admin of the list can accept emails from a given email address. Sorry, I can't remember exactly what I had to do to get mine to work.

**Comment by keean** [comment]
I have set up the mailing list:
```
zenscript-builds@googlegroups.com
```
It is a private mailing list that anyone can ask to join, that receives notifications of repository pushes for Zen.

**Comment by skaller** [comment]
> On 10 Oct 2016, at 03:32, Keean Schupke <notifications@github.com> wrote:
> 
> I have set up the mailing list:
> 
> zenscript-builds@googlegroups.com
> 
> It is a private mailing list that anyone can ask to join, that receives notifications of repository pushes for Zen.

Hmm, i can’t find it.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by keean** [comment]
I have added it to the list directory, so you should be able to search for it now.

**Comment by shelby3** [comment]
Can someone please explain to me the issue, what was necessary, why, and what has been done? It is as you all are speaking a private language which I don't grok.

I gather @skaller doesn't like to use the GUI interface and wants to receive all information via email? And there is some difficulty in achieving that which required @keean to add some service?

Github doesn't provide what he wants? Why?

**Comment by skaller** [comment]
> On 10 Oct 2016, at 20:37, shelby3 <notifications@github.com> wrote:
> 
> Can someone please explain to me the issue, what was necessary, why, and what has been done? It is as you all are speaking a private language which I don't grok.
> 
> I gather @skaller doesn’t like to use the GUI interface and wants to receive all information via email?

At this time I do not want email about ALL the issues. Its too much, and I don’t know
enough. I would like to start writing actual, supported, parts of the language as they’re
developed, as test cases.

I will require suitable instruction on what is implemented and what it is supposed to do.
This would be useful documentation for others as well.

I may take an interest in wider issues later when I have a better feel for the system.

Email suits me best as a medium because it is off line and cheap.
It also allows responding to a particular email with quotation, the issue lists don’t.

> And there is some difficulty in achieving that which required @keean to add some service?

Yes. There’s no option to just see commits plus selected issues.

> Github doesn't provide what he wants? Why?

No, and, you would have to ask GitHub.

Githb will send commit information to zero, one, or two mailing addresses.
The intent is that these are email lists those interested can subscribe to.
Keean created such a list on gmail:

	zenscript-builds@googlegroups.com

Unfortunately I cant find it at the moment :)

@Keaan: it HAS TO BE A PUBLIC GROUP. Private groups can only be
accessed by gmail accounts. I have one but I do not use it for email.

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by shelby3** [comment]
@skaller wrote:
> Githb will send commit information to zero, one, or two mailing addresses.
The intent is that these are email lists those interested can subscribe to.

Ah I see now. Before I thought you meant that your Github account would only allow you to have two email addresses for notification. And I was wondering why that was insufficient for you.

**Comment by keean** [comment]
Closing as this is now set up, and seems to be working.
