### ISSUE TITLE
Type Constructor Syntax

### ISSUE THREAD

**Issue by keean** [keean/zenscript#7]
There are four obvious options:

Java style: `Add<a, a>`
Scala style: `Add[a, a]`
Haskell style: `Add a a`
Prolog style: `Add(a, a)`

Which option should we go for?

**Comment by johnwcowan** [comment]
Assuming you use parentheses for something else, I would favor either Java or Scala style.

**Comment by shelby3** [comment]
If we use `[ ... ]` as sugar for constructing and (in pattern matching) destructuring arrays, then unless we are using `< ... >` for something that appears very often in the code, I would lean towards the Java/C++ style, and it also has a longer history. But there might some conflict in the grammar that favors `[` over `<`. Let's see when we have the entire grammar sorted out.

**Comment by keean** [comment]
I think we can stick with the Java way, although the Haskell syntax is more concise.

**Comment by shelby3** [comment]
@keean wrote:
> although the Haskell syntax is more concise.

[I argued](https://github.com/keean/zenscript/issues/5#issuecomment-248463765) that it is confusing and maybe has similar issues as to why I argued for explicit parenthesis for function calls.

**Comment by shelby3** [comment]
@keean if ever you feel you would rather create a more Haskell-like syntax, then please don't be shy to tell me. I am hoping we can agree on the design. But if ever we can't, it is better to know than let it fester unstated.

**Comment by keean** [comment]
Okay I think that's agreed. If we wanted a recursive expression type it would be written something like:
```
type Exp = (Num | Add<a, a> | Mul<a, a>) as a
```
We can also make the expression type parametric on the type of the expression like this:
```
type Exp<a> = (Lit<a> | Add<b, b> | Mul<b, b>) as b
```

>if ever you feel you would rather create a more Haskell-like syntax, then please don't be shy to tell me

I like Rust too :-) I think its going well, and I like the decisions we have made so far .

**Comment by shelby3** [comment]
@keean wrote:
> If we wanted a recursive expression type it would be written something like:
> 
> type Exp = (Num | Add<a, a> | Mul<a, a>) as a

I had [agreed on that](https://github.com/keean/zenscript/issues/5#issuecomment-248463765) syntax already.

**Comment by shelby3** [comment]
@keean [wrote](https://github.com/keean/zenscript/issues/5#issuecomment-248570943):
> I have written a lot in both styles, my only objection to `<` and `>` is that they are not really brackets and don't often get bracket matching in UI, and cause problems with cut and paste into HTML.

Ah yes, I had forgotten about those issues with angle brackets which are treated as less than and greater than in some contexts and yes the breakage of not escaping to HTML entity &lt;.

But that HTML breakage applies to any code that has a less than symbol as well. So I rule that out as a valid concern.

And UIs not treating them as angle brackets when the file extension is a programming language, seems to be sort of worrying about the fringes of possible concerns? We'll probably have many issues on the fringes that we can't make perfect. I am thinking in terms of priorities.

**Comment by shelby3** [comment]
Why is the title of this issue, "Type Constructor Syntax"? What does that mean?

It seems the OP is about type parameter syntax.

**Comment by keean** [comment]
The type-consructor is the bit like `Add`. It is clearly not a type, and only becomes a type when it's parameters are provided, so `Add<Num, Num>` is a type, and `Add` is a type constructor. I think it can be a type if you allow higher kinded types, and then it would be a type of kind * -> * -> *

**Comment by keean** [comment]
I think this is decided, will reopen if there are further issues.

**Comment by shelby3** [comment]
Please add a label for the resolution thus far. "Accepted"?

**Comment by keean** [comment]
Yes, I am on my mobile at the moment and can't see how to do it. Will mark when I get home. Is accepted or decided better?

**Comment by shelby3** [comment]
@keean wrote:
> The type-consructor is the bit like `Add`.

I see you are referring to [kinds](https://en.wikipedia.org/wiki/Kind_(type_theory)). I was conflating with instance construction.

**Comment by shelby3** [comment]
For consistency, "Accepted" seems adequate to me. A proposal was put forward to choose a syntax analogous to a proposal being put forward to choose a better name than TraitScript. This proposal was decided and accepted.

**Comment by shelby3** [comment]
@keean wrote:
> The type-consructor is the bit like `Add`.

Ah, you are referring to [kinds](https://en.wikipedia.org/wiki/Kind_(type_theory)). I was conflating with instance construction?

**Edit:** now I remember my confusion. The type parameter syntax also applies to functions, not just to kinds. So it seems the title of the Issue is incorrect. You could edit it, to make it more clear it about type parameter declaration, not something about kinds.

**Comment by shelby3** [comment]
@keean wrote:
> The type-consructor is the bit like `Add`.

Ah, you are referring to [kinds](https://en.wikipedia.org/wiki/Kind_(type_theory)). I was conflating with instance construction?

**Edit:** now I remember my confusion. The type parameter syntax might also apply to functions (if we don't choose [my proposed less verbose type parameter syntax for functions](https://github.com/keean/zenscript/issues/6#issuecomment-248742773)), not just to kinds. So it seems the title of the Issue is incorrect. You could edit it, to make it more clear it about type parameter declaration, not something about kinds.

**Comment by shelby3** [comment]
@shelby3 wrote:
> For consistency, "Accepted" seems adequate to me. A proposal was put forward to choose a syntax analogous to a proposal being put forward to choose a better name than TraitScript. This proposal was decided and accepted.

On further thought, you could use "Decided" to differentiate when the discussion was not a proposal that could be denied, but rather a discussion that had to be reach mutual agreement. For example, when we eventually close the "Subtyping" Issue #8.

**Comment by shelby3** [comment]
Reminding to attach a label "Decided" to this closed Issue.
