### ISSUE TITLE
Objects or No Objects

### ISSUE THREAD

**Issue by keean** [keean/zenscript#9]
Discussion about records vs objects

**Comment by shelby3** [comment]
Please define the terms and they are not the same thing?

**Comment by shelby3** [comment]
[Link to](https://github.com/keean/zenscript/issues/1#issuecomment-249290773) potentially relevant discussion?

**Comment by keean** [comment]
If you read the OOHaskell paper you will find that an object is the fixed point of a record. However I in general prefer to separate data and functions. 

A record is like a namespace, and a value of a record type is a particular implementation or value. In basic terms a record is like a `C` struct.

**Comment by shelby3** [comment]
@keean wrote:
> If you read the OOHaskell paper you will find that an object is the fixed point of a record.

Are you referring to [page 15](http://camlunity.ru/swap/Library/Computer%20Science/Haskell/Haskell's%20Overlooked%20Object%20System.pdf#page=15), where setting the tail to the Unit type?

Again this seems to be a conclusion that is specific to Haskell's type system and how you are representing inheritance? And what does inheritance have to do with objects?

**Comment by keean** [comment]
I think we are agreed to have simple objects. No inheritance just interfaces/type classes. Closing as decided.

**Comment by shelby3** [comment]
You mean no virtual inheritance and no subclassing. But what about typeclass objects? And what about unions being subtypes? I don't think we can nail down those yet?

**Comment by keean** [comment]
I think the conclusion here is we are having objects, which will be at least simple objects. The other things are the subject of other threads, but to cover my thoughts, I don't think we need typeclass objects because we have union types. By no inheritance I mean you cannot extend object A. You can extend a typeclass but that is something different. We have interface inheritance, but not implementation inheritance.

**Comment by shelby3** [comment]
@shelby wrote:
> I don't think we need typeclass objects because we have union types.

[Disagree](https://github.com/keean/zenscript/issues/14#issuecomment-251634208).
